language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
#    - cubrid/9.3.0
    - vendor
    - $HOME/.composer/cache

install:
  - |
    if [ $TRAVIS_PHP_VERSION != '5.6' ]; then
        # disable xdebug for performance reasons when code coverage is not needed
        phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi
  - travis_retry composer self-update && composer --version && composer install
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer update --prefer-dist --no-interaction

before_script:
  # show some versions and env information
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - mysql --version
  - psql --version

  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

script:
  # validate composer.json
  - composer validate --no-check-lock
  - cd framework && composer validate --no-check-lock && cd ..
  # run PHPUnit
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --exclude-group mssql,oci,wincache,xcache,zenddata,cubrid

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi