language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
install:
  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  - composer install